### PR TITLE
migrate from travis/av to github actions

### PR DESCRIPTION
**Pull request by lucaferranti**

### CODE REVIEW

**Comment by lucaferranti** [comment]
ok the migration should be set up now. Here a summary of the new workflow, let me know if I need to change something
- tests on julia 1.5, 1.6, nightly
- it allows failure on nightly
- tests on ubuntu (x86, x64), macOS (x64) and windows (x86, x64)
- uses codecov for coverage
- does not deploy the docs with documenter, as the docs folder for this repo doesn't have any content. #57 adds a link to the docs in the webpage.

At the moment it seems that the tests fail on windows with 1.6 and nightly, but I guess that's a package issue and not a workflow issue.  Maybe we could temporarily remove tests on 1.6 or allow failure on it and investigate this issue in a dedicated branch?

Also, I am not sure why appveyor was triggered even though I removed the `appveyor.yml` file. Maybe something needs to be changed in the settings? I'll try to figure this out.

**Comment by lbenet** [comment]
> Also, I am not sure why appveyor was triggered even though I removed the appveyor.yml file. Maybe something needs to be changed in the settings? I'll try to figure this out.

I think @dpsanders has to deactivate appveyor from his account there. The same has to be done in TaylorModels: see https://github.com/JuliaIntervals/TaylorModels.jl/pull/102

**Comment by dpsanders** [comment]
@lucaferranti OK I guess we can remove 1.6 temporarily.

**Comment by lucaferranti** [comment]
the last commit added link to docs in the website. fixes #3

**Pull request merged**
