### PR TITLE
Adding Project.toml

### PR DESCRIPTION
**Pull request by yashvardhan747**

### CODE REVIEW

**Comment by dpsanders** [comment]
I would suggest putting the minimum Julia version to 1.0. You also need to add a version number (0.4)

**Comment by dpsanders** [comment]
And you can remove the require file

**Comment by yashcodes** [comment]
Version 0.4 of what ?

**Comment by dpsanders** [comment]
Version 0.4 of IntervalOptimisation.jl

**Comment by dpsanders** [comment]
Ah we are dropping support for Julia 0. 7 so it should be version 0.4. This is what you should say in news.md

**Comment by yashcodes** [comment]
ok I'll correct it

**Comment by dpsanders** [comment]
Thanks!

**Comment by dpsanders** [comment]
@JuliaRegistrator register()

**Pull request merged**
