### PR TITLE
SortedVector.jl is modified

### PR DESCRIPTION
**Pull request by yashcodes**
Fixes [#18](https://github.com/JuliaIntervals/IntervalOptimisation.jl/issues/18)

### CODE REVIEW

**Comment by dpsanders** [comment]
Thanks! For any PR, please describe in the comment briefly what the change is, and always add tests.

**Comment by dpsanders** [comment]
In this case, it fixes issue #18, so you can write

```
Fixes #18 
```
in the first comment in the PR, so that that issue should be automatically closed if the PR is merged.

**Comment by yashcodes** [comment]
Oh sorry for mistake. I'll do it in correct way.

**Comment by yashcodes** [comment]
done.

**Comment by dpsanders** [comment]
Thanks a lot!

**Pull request merged**
